[2025-03-15T10:32:29.706+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T10:32:29.713+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training-pipeline.validation_task manual__2025-03-15T10:32:13.530486+00:00 [queued]>
[2025-03-15T10:32:29.715+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training-pipeline.validation_task manual__2025-03-15T10:32:13.530486+00:00 [queued]>
[2025-03-15T10:32:29.715+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-15T10:32:29.719+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): validation_task> on 2025-03-15 10:32:13.530486+00:00
[2025-03-15T10:32:29.722+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T10:32:29.723+0000] {standard_task_runner.py:72} INFO - Started process 168 to run task
[2025-03-15T10:32:29.723+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'training-pipeline', 'validation_task', 'manual__2025-03-15T10:32:13.530486+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpbnnb94ga']
[2025-03-15T10:32:29.724+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask validation_task
[2025-03-15T10:32:29.740+0000] {task_command.py:467} INFO - Running <TaskInstance: training-pipeline.validation_task manual__2025-03-15T10:32:13.530486+00:00 [running]> on host a3f135322fa9
[2025-03-15T10:32:29.763+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='training-pipeline' AIRFLOW_CTX_TASK_ID='validation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T10:32:13.530486+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T10:32:13.530486+00:00'
[2025-03-15T10:32:29.763+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T10:32:29.772+0000] {condition_step.py:38} INFO - Run_id: 9aef53a7ca004fa396b1cfbdd5a68c4d
[2025-03-15T10:32:29.812+0000] {condition_step.py:57} INFO - No registered models found. Registering a new model...
[2025-03-15T10:32:29.815+0000] {logging_mixin.py:190} WARNING - Registered model 'cancellation_estimator' already exists. Creating a new version of this model...
[2025-03-15T10:32:29.827+0000] {logging_mixin.py:190} WARNING - 2025/03/15 10:32:29 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: cancellation_estimator, version 2
[2025-03-15T10:32:29.827+0000] {logging_mixin.py:190} WARNING - Created version '2' of model 'cancellation_estimator'.
[2025-03-15T10:32:29.827+0000] {condition_step.py:62} INFO - New model registered.
[2025-03-15T10:32:29.827+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-15T10:32:29.831+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T10:32:29.831+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=training-pipeline, task_id=validation_task, run_id=manual__2025-03-15T10:32:13.530486+00:00, execution_date=20250315T103213, start_date=20250315T103229, end_date=20250315T103229
[2025-03-15T10:32:29.863+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-15T10:32:29.869+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T10:32:29.870+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
